#!/bin/bash
echo "321USA"



curl -sSL https://github.com/v2ray/v2ray-core/releases/download/v3.21/v2ray-linux-64.zip -o new.zip
unzip new.zip
cd  v2ray*
echo -e -n "$CONFIG_JSON1" > config.json
echo -e -n "$PORT" >> config.json
echo -e -n "$CONFIG_JSON2" >> config.json
echo -e -n "$UUID" >> config.json
echo -e -n "$CONFIG_JSON3" >> config.json
if [ "$CERT_PEM" != "$KEY_PEM" ]; then
echo -e "$CERT_PEM" > cert.pem
echo -e "$KEY_PEM"  > key.pem
fi
./v2ray

while :; do sleep 31104000 ; done
